services:
  - type: web
    name: fe-plantshop-backup
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
